<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DepositMethodsSeeder extends Seeder
{
    public function run()
    {
        $depositMethods = [
            [
                'id' => 1,
                'payment_gateway_id' => 1,
                'logo' => 'general/images/QXRsRuDK7CE75qFdx6th.png',
                'name' => 'Paypal USD',
                'type' => 'auto',
                'method_code' => 'paypal-usd',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'min_deposit' => 100,
                'max_deposit' => 2000,
                'conversion_rate_live' => 0,
                'conversion_rate' => 1,
                'charge_type' => 'fixed',
                'charge' => 20,
                'fields' => null,
                'receive_payment_details' => null,
                'status' => 1,
                'created_at' => '2024-08-15 20:38:54',
                'updated_at' => '2024-09-22 07:17:55',
            ],
            [
                'id' => 2,
                'payment_gateway_id' => null,
                'logo' => 'general/images/015sjEOt8t5bweX741B5.png',
                'name' => 'Mobile Money',
                'type' => 'manual',
                'method_code' => 'mobile-money',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'min_deposit' => 10,
                'max_deposit' => 10000,
                'conversion_rate_live' => null,
                'conversion_rate' => 1,
                'charge_type' => 'fixed',
                'charge' => 20,
                'fields' => '[{"name":"Transaction id","type":"text","validation":"required"},{"name":"Screenshot","type":"file","validation":"nullable"}]',
                'receive_payment_details' => '<p>Kindly transfer the payment to the Mobile Money number below:</p><p>Mobile Money Number: 000-000-000-000-000</p>',
                'status' => 1,
                'created_at' => '2024-08-15 20:42:57',
                'updated_at' => '2024-10-22 21:23:52',
            ],
            [
                'id' => 3,
                'payment_gateway_id' => null,
                'logo' => 'general/images/KvEL096y2omjhj685nbI.png',
                'name' => 'Bank Wire',
                'type' => 'manual',
                'method_code' => 'bank-wire',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'min_deposit' => 100,
                'max_deposit' => 200000,
                'conversion_rate_live' => null,
                'conversion_rate' => 117,
                'charge_type' => 'percent',
                'charge' => 5,
                'fields' => '[{"name":"Account Number","type":"text","validation":"required"}]',
                'receive_payment_details' => '<p>Please send the payment to the following bank details:</p><p><b>Bank Name</b>: Demo Test </p><p><b>Bank Account Name:</b> Demo</p><p><b>Account Number:</b> 000-000-000-000-000</p><p><b>Routing Number:</b> 0123456789</p>',
                'status' => 1,
                'created_at' => '2024-08-15 22:06:01',
                'updated_at' => '2024-10-22 20:43:50',
            ],
            [
                'id' => 4,
                'payment_gateway_id' => 2,
                'logo' => null,
                'name' => 'Stripe USD',
                'type' => 'auto',
                'method_code' => 'stripe-usd',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'min_deposit' => 10,
                'max_deposit' => 1000,
                'conversion_rate_live' => 0,
                'conversion_rate' => 1,
                'charge_type' => 'percent',
                'charge' => 2,
                'fields' => null,
                'receive_payment_details' => null,
                'status' => 1,
                'created_at' => '2024-10-20 21:24:51',
                'updated_at' => '2024-10-21 22:23:54',
            ],
            [
                'id' => 5,
                'payment_gateway_id' => 3,
                'logo' => null,
                'name' => 'Mollie USD',
                'type' => 'auto',
                'method_code' => 'mollie-usd',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'min_deposit' => 10,
                'max_deposit' => 10000,
                'conversion_rate_live' => 0,
                'conversion_rate' => 1,
                'charge_type' => 'fixed',
                'charge' => 5,
                'fields' => null,
                'receive_payment_details' => null,
                'status' => 1,
                'created_at' => '2024-10-21 02:21:33',
                'updated_at' => '2024-10-21 04:05:33',
            ],
            [
                'id' => 6,
                'payment_gateway_id' => 4,
                'logo' => null,
                'name' => 'Perfect Money Usd',
                'type' => 'auto',
                'method_code' => 'perfectmoney-usd',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'min_deposit' => 10,
                'max_deposit' => 10000,
                'conversion_rate_live' => 0,
                'conversion_rate' => 1,
                'charge_type' => 'percent',
                'charge' => 2,
                'fields' => null,
                'receive_payment_details' => null,
                'status' => 1,
                'created_at' => '2024-10-21 05:29:56',
                'updated_at' => '2024-10-22 21:07:41',
            ],
            [
                'id' => 7,
                'payment_gateway_id' => 5,
                'logo' => null,
                'name' => 'Coinbase Usd',
                'type' => 'auto',
                'method_code' => 'coinbase-usd',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'min_deposit' => 10,
                'max_deposit' => 1000,
                'conversion_rate_live' => 0,
                'conversion_rate' => 1,
                'charge_type' => 'percent',
                'charge' => 2,
                'fields' => null,
                'receive_payment_details' => null,
                'status' => 1,
                'created_at' => '2024-10-21 10:08:51',
                'updated_at' => '2024-10-22 21:07:50',
            ],
            [
                'id' => 8,
                'payment_gateway_id' => null,
                'logo' => 'general/images/AgksgswH0xsqAwdLMG1y.png',
                'name' => 'Tether (USDT)',
                'type' => 'manual',
                'method_code' => 'usdt',
                'currency' => 'USDT',
                'currency_symbol' => '₮',
                'min_deposit' => 5,
                'max_deposit' => 1000,
                'conversion_rate_live' => null,
                'conversion_rate' => 1,
                'charge_type' => 'percent',
                'charge' => 2,
                'fields' => '[{"name":"Hash Address","type":"text","validation":"required"},{"name":"Screenshot","type":"file","validation":"required"}]',
                'receive_payment_details' => '<p>Please send the USDT to the address below:</p><p>Address: <span>0xdAC17F958D2ee523a2206206994597C13D831ec7</span><br></p>',
                'status' => 1,
                'created_at' => '2024-10-22 19:15:23',
                'updated_at' => '2024-10-22 21:23:34',
            ],
        ];

        foreach ($depositMethods as $method) {
            DB::table('deposit_methods')->insert($method);
        }
    }
}
