<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NotifyTemplatesSeeder extends Seeder
{
    public function run()
    {
        DB::table('notify_templates')->insert([
            [
                'id' => 1,
                'icon' => 'deposit',
                'name' => 'Deposit Notify',
                'code' => 'deposit_user',
                'info' => 'Notify user when deposit is successful',
                'type' => 'user',
                'subject' => 'Deposit Notify',
                'push_message' => 'Your deposit of {$amount} has been successful.',
                'mail_message' => 'Hello, your deposit of {$amount} has been processed successfully. Type: {$type}.',
                'variables' => 'amount,type',
                'mail_status' => 0,
                'push_status' => 1,
                'created_at' => '2024-10-14 15:07:32',
                'updated_at' => '2024-10-15 10:30:22',
            ],
            [
                'id' => 2,
                'icon' => 'deposit-action',
                'name' => 'Deposit Action Notify',
                'code' => 'deposit_action_user',
                'info' => 'Notify user when deposit request is rejected or approved',
                'type' => 'user',
                'subject' => 'Deposit Action Notify',
                'push_message' => 'Your deposit request of {$amount} has been {$status}.',
                'mail_message' => 'Dear user, your deposit request of {$amount} has been {$status}. Type: {$type}.',
                'variables' => 'amount,type,status',
                'mail_status' => 0,
                'push_status' => 1,
                'created_at' => '2024-10-14 15:07:32',
                'updated_at' => '2024-10-15 10:30:06',
            ],
            [
                'id' => 3,
                'icon' => 'deposit',
                'name' => 'Deposit Notify',
                'code' => 'deposit_admin',
                'info' => 'Notify admin when user deposits successfully',
                'type' => 'admin',
                'subject' => 'Deposit Notify',
                'push_message' => '{$amount} has been deposited via {$method} by {$user_name}.',
                'mail_message' => 'Dear Admin, {$user_name} has deposited {$amount} via {$method}. Type: {$type}.',
                'variables' => 'user_name,amount,type,method',
                'mail_status' => 0,
                'push_status' => 1,
                'created_at' => '2024-10-14 15:07:32',
                'updated_at' => '2024-10-15 17:57:32',
            ],
            [
                'id' => 4,
                'icon' => 'deposit-action',
                'name' => 'Deposit Action Notify',
                'code' => 'deposit_action_admin',
                'info' => 'Notify admin after user submits a manual deposit request',
                'type' => 'admin',
                'subject' => 'Deposit Action Notify',
                'push_message' => '{$amount} has been deposited via {$method} by {$user_name}.',
                'mail_message' => 'Dear Admin, the user {$user_name} has deposited {$amount} via {$method}. Type: {$type}.',
                'variables' => 'user_name,amount,type,method',
                'mail_status' => 0,
                'push_status' => 1,
                'created_at' => '2024-10-14 15:07:32',
                'updated_at' => '2024-10-15 17:56:14',
            ],
            [
                'id' => 5,
                'icon' => 'service',
                'name' => 'Service Notify',
                'code' => 'service_user',
                'info' => 'Notify user when service is bought successfully',
                'type' => 'user',
                'subject' => 'Service Notify',
                'push_message' => 'Your service {$service_name} has been purchased successfully for {$amount}.',
                'mail_message' => 'Dear user, your service purchase of {$service_name} for {$amount} has been successful. Type: {$type}.',
                'variables' => 'service_name,amount,type',
                'mail_status' => 0,
                'push_status' => 1,
                'created_at' => '2024-10-14 15:07:32',
                'updated_at' => '2024-10-15 10:30:22',
            ],
            [
                'id' => 6,
                'icon' => 'service-1',
                'name' => 'Service Action Notify',
                'code' => 'service_action_user',
                'info' => 'Notify user after service request is processed with manual payment method',
                'type' => 'user',
                'subject' => 'Service Action Notify',
                'push_message' => 'Service request for {$service_name} has been processed with status: {$status}',
                'mail_message' => 'Your request for the service {$service_name} with amount {$amount} has been processed. Status: {$status}. Type: {$type}.',
                'variables' => 'service_name,amount,type,status',
                'mail_status' => 0,
                'push_status' => 1,
                'created_at' => '2024-10-14 15:07:32',
                'updated_at' => '2024-10-16 01:17:07',
            ],
            [
                'id' => 7,
                'icon' => 'service',
                'name' => 'Service Notify',
                'code' => 'service_admin',
                'info' => 'Notify admin when service is bought successfully',
                'type' => 'admin',
                'subject' => 'Service Notify',
                'push_message' => 'Service {$service_name} purchased by {$user_name} for {$amount} via {$method}.',
                'mail_message' => 'Dear Admin, {$user_name} has purchased {$service_name} for {$amount} via {$method}. Type: {$type}.',
                'variables' => 'user_name,service_name,amount,type,method',
                'mail_status' => 0,
                'push_status' => 1,
                'created_at' => '2024-10-14 15:07:32',
                'updated_at' => '2024-10-15 10:30:22',
            ],
            [
                'id' => 8,
                'icon' => 'service-1',
                'name' => 'Service Action Notify',
                'code' => 'service_action_admin',
                'info' => 'Notify admin after user submits manual service request',
                'type' => 'admin',
                'subject' => 'Service Action Notify',
                'push_message' => 'Manual service request from {$user_name} for {$service_name} has been submitted.',
                'mail_message' => 'Dear Admin, the user {$user_name} has submitted a manual service request for {$service_name}. Amount: {$amount}, Type: {$type}, Method: {$method}.',
                'variables' => 'user_name,service_name,amount,type,method',
                'mail_status' => 0,
                'push_status' => 1,
                'created_at' => '2024-10-14 15:07:32',
                'updated_at' => '2024-10-15 10:30:22',
            ],
            [
                'id' => 9,
                'icon' => 'subscription',
                'name' => 'Subscription Notify',
                'code' => 'subscription_user',
                'info' => 'Notify user when subscription is successful',
                'type' => 'user',
                'subject' => 'Subscription Notify',
                'push_message' => 'Your subscription of {$amount} has been successful.',
                'mail_message' => 'Dear user, your subscription of {$amount} has been successful. Type: {$type}.',
                'variables' => 'amount,type',
                'mail_status' => 0,
                'push_status' => 1,
                'created_at' => '2024-10-14 15:07:32',
                'updated_at' => '2024-10-15 10:30:22',
            ],
            [
                'id' => 10,
                'icon' => 'subscription-1',
                'name' => 'Subscription Action Notify',
                'code' => 'subscription_action_user',
                'info' => 'Notify user after subscription request is processed with manual payment method',
                'type' => 'user',
                'subject' => 'Subscription Action Notify',
                'push_message' => 'Subscription request processed with status: {$status}.',
                'mail_message' => 'Your subscription request for {$amount} has been processed. Status: {$status}. Type: {$type}.',
                'variables' => 'amount,type,status',
                'mail_status' => 0,
                'push_status' => 1,
                'created_at' => '2024-10-14 15:07:32',
                'updated_at' => '2024-10-15 10:30:22'
            ],
            [
                'id' => 11,
                'icon' => 'subscription',
                'name' => 'Subscription Notify',
                'code' => 'subscription_admin',
                'info' => 'Notify admin when subscription is successful',
                'type' => 'admin',
                'subject' => 'Subscription Notify',
                'push_message' => 'Subscription from {$user_name} for {$amount} has been successful.',
                'mail_message' => 'Dear Admin, {$user_name} has subscribed for {$amount} via {$method}. Type: {$type}.',
                'variables' => 'user_name,amount,type,method',
                'mail_status' => 0,
                'push_status' => 1,
                'created_at' => '2024-10-14 15:07:32',
                'updated_at' => '2024-10-15 10:30:22'
            ],
            [
                'id' => 12,
                'icon' => 'subscription-1',
                'name' => 'Subscription Action Notify',
                'code' => 'subscription_action_admin',
                'info' => 'Notify admin after user submits subscription request',
                'type' => 'admin',
                'subject' => 'Subscription Action Notify',
                'push_message' => '{$user_name} has submitted a manual subscription request.',
                'mail_message' => 'Dear Admin, the user {$user_name} has submitted a manual subscription request for {$amount} via {$method}. Type: {$type}.',
                'variables' => 'user_name,amount,type,method',
                'mail_status' => 0,
                'push_status' => 1,
                'created_at' => '2024-10-14 15:07:32',
                'updated_at' => '2024-10-15 10:30:22'
            ],
            [
                'id' => 13,
                'icon' => 'wallet-2',
                'name' => 'Balance Updated Notify',
                'code' => 'balance_updated_user',
                'info' => 'Notify user when balance is updated',
                'type' => 'user',
                'subject' => 'Balance Updated Notify',
                'push_message' => 'Your balance has been updated. New amount: {$amount}.',
                'mail_message' => 'Dear user, your balance has been updated. New amount: {$amount}. Type: {$type}.',
                'variables' => 'amount,type',
                'mail_status' => 0,
                'push_status' => 1,
                'created_at' => '2024-10-14 15:07:32',
                'updated_at' => '2024-10-15 10:30:22'
            ],
            [
                'id' => 14,
                'icon' => 'chat',
                'name' => 'Support Notify',
                'code' => 'support_user',
                'info' => 'Notify user when support ticket is replied',
                'type' => 'user',
                'subject' => 'Support Notify',
                'push_message' => 'Your support ticket {$ticket_number} in {$category} has been updated with status: {$status}.',
                'mail_message' => 'Dear user, your support ticket {$ticket_number} for category {$category} has been updated. Status: {$status}. Type: {$type}.',
                'variables' => 'type,status,ticket_number,category',
                'mail_status' => 0,
                'push_status' => 1,
                'created_at' => '2024-10-14 15:07:32',
                'updated_at' => '2024-10-15 10:30:22'
            ],
            [
                'id' => 15,
                'icon' => 'chat',
                'name' => 'Support Notify',
                'code' => 'support_admin',
                'info' => 'Notify admin when support ticket is created by user',
                'type' => 'admin',
                'subject' => 'Support Notify',
                'push_message' => 'New support ticket {$ticket_number} from {$user_name} in {$category}.',
                'mail_message' => 'Dear Admin, {$user_name} has created a new support ticket (Ticket No: {$ticket_number}, Type: {$ticket_type}, Category: {$category}). Status: {$status}.',
                'variables' => 'user_name,ticket_type,type,status,ticket_number,category',
                'mail_status' => 0,
                'push_status' => 1,
                'created_at' => '2024-10-14 15:07:32',
                'updated_at' => '2024-10-15 10:30:22'
            ]
        ]);
    }
}
