<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PagesSeeder extends Seeder
{
    public function run()
    {
        DB::table('pages')->insert([
            [
                'id' => 1,
                'is_breadcrumb' => 0,
                'title' => 'Home',
                'slug' => '/',
                'component_id' => '["1","2","3","4","5","6","7","8","9","10"]',
                'type' => 'static',
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'created_at' => '2024-03-05 06:58:05',
                'updated_at' => '2024-10-22 18:34:01',
            ],
            [
                'id' => 3,
                'is_breadcrumb' => 1,
                'title' => 'Blog',
                'slug' => 'blog',
                'component_id' => '["11"]',
                'type' => 'dynamic',
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'created_at' => '2024-03-15 18:17:34',
                'updated_at' => '2024-05-09 06:04:16',
            ],
            [
                'id' => 4,
                'is_breadcrumb' => 1,
                'title' => 'About',
                'slug' => 'about',
                'component_id' => '["12","13","5","14"]',
                'type' => 'dynamic',
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'created_at' => '2024-03-18 00:34:34',
                'updated_at' => '2024-03-18 02:23:59',
            ],
            [
                'id' => 5,
                'is_breadcrumb' => 1,
                'title' => 'Service',
                'slug' => 'service',
                'component_id' => '["15"]',
                'type' => 'dynamic',
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'created_at' => '2024-03-18 17:11:51',
                'updated_at' => '2024-03-18 17:11:51',
            ],
            [
                'id' => 6,
                'is_breadcrumb' => 1,
                'title' => 'Contact',
                'slug' => 'contact',
                'component_id' => '["17"]',
                'type' => 'dynamic',
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'created_at' => '2024-03-20 01:20:29',
                'updated_at' => '2024-05-17 05:05:33',
            ],
            [
                'id' => 7,
                'is_breadcrumb' => 1,
                'title' => 'FAQ',
                'slug' => 'faq',
                'component_id' => '["16"]',
                'type' => 'dynamic',
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'created_at' => '2024-03-21 02:55:37',
                'updated_at' => '2024-03-21 02:55:37',
            ],
            [
                'id' => 8,
                'is_breadcrumb' => 1,
                'title' => 'Terms & Condition',
                'slug' => 'terms-condition',
                'component_id' => '["46"]',
                'type' => 'dynamic',
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'created_at' => '2024-03-22 00:00:49',
                'updated_at' => '2024-05-13 00:32:46',
            ],
            [
                'id' => 9,
                'is_breadcrumb' => 1,
                'title' => 'Privacy Policy',
                'slug' => 'privacy-policy',
                'component_id' => '["32"]',
                'type' => 'dynamic',
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'created_at' => '2024-03-22 00:28:29',
                'updated_at' => '2024-04-24 22:51:40',
            ],
            [
                'id' => 11,
                'is_breadcrumb' => 0,
                'title' => 'Home 2',
                'slug' => 'home-2',
                'component_id' => '["18","20","29","5","21","13","49","22","23","10"]',
                'type' => 'dynamic',
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'created_at' => '2024-05-09 04:35:11',
                'updated_at' => '2024-05-11 20:19:56',
            ],
            [
                'id' => 12,
                'is_breadcrumb' => 0,
                'title' => 'home-3',
                'slug' => 'home-3',
                'component_id' => '["19","12","30","24","14","16","25","26","27","28"]',
                'type' => 'dynamic',
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'created_at' => '2024-05-11 21:28:19',
                'updated_at' => '2024-05-12 04:53:45',
            ],
            [
                'id' => 13,
                'is_breadcrumb' => 0,
                'title' => 'Dark Home',
                'slug' => 'dark-home',
                'component_id' => '["19","31","12","30","24","14","16","25","26","27","28"]',
                'type' => 'dynamic',
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'created_at' => '2024-05-14 23:13:46',
                'updated_at' => '2024-05-14 23:17:46',
            ]
        ]);
    }
}