<?php $__env->startSection('title', __('My Services')); ?><?php $__env->startSection('user-content'); ?>    <div class="card border-0 mb-4">        <div class="card-body px-2">            <div class="table-responsive rounded mb-3">                <table class="table card-table table-vcenter text-nowrap mb-0">                    <thead class="table-light">                    <tr>                        <th><?php echo e(__('service Name') .' | ' . __('Order Date')); ?></th>                        <th><?php echo e(__('Order Number') .' | ' . __('Price')); ?></th>                        <th><?php echo e(__('Working Status')); ?></th>                        <th><?php echo e(__('Payment Status')); ?></th>                        <th><?php echo e(__('Details')); ?></th>                    </tr>                    </thead>                    <tbody>                    <?php $__currentLoopData = $orders; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $order): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>                        <?php                            $workingStatus = ['pending' => 'info', 'working' => 'cyan', 'completed' => 'success', 'cancel' => 'danger'][$order->status] ?? 'blue';                            $transactionStatus = ['pending' => 'info', 'completed' => 'success', 'failed' => 'danger'][$order->transaction->status] ?? 'blue';                        ?>                        <tr class="align-middle">                            <td>                                <div class="fw-bold"><?php echo e(_tr($order->service->name)); ?></div>                                <div class="text-muted small"><?php echo e(ucwords($order->created_at_time)); ?></div>                            </td>                            <td>                                <div class="fw-bold"><?php echo e($order->order_number); ?></div>                                <div class="text-muted small"><?php echo e(setting('currency_symbol') . ucwords($order->transaction->amount . ' ' . setting('site_currency'))); ?></div>                            </td>                            <td>                                <span class="badge bg-<?php echo e($workingStatus); ?> text-<?php echo e($workingStatus); ?>-fg"><?php echo e(strtoupper($order->status)); ?></span>                            </td>                            <td>                                <span class="badge bg-<?php echo e($transactionStatus); ?> text-<?php echo e($transactionStatus); ?>-fg"><?php echo e(strtoupper($order->transaction->status)); ?></span>                            </td>                            <td>                                <a href="<?php echo e(route('user.service.task-board', $order->id)); ?>" class="btn btn-primary">                                    <?php if (isset($component)) { $__componentOriginalce262628e3a8d44dc38fd1f3965181bc = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginalce262628e3a8d44dc38fd1f3965181bc = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.icon','data' => ['name' => 'task','height' => '20']] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? (array) $attributes->getIterator() : [])); ?>
<?php $component->withName('icon'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag && $constructor = (new ReflectionClass(Illuminate\View\AnonymousComponent::class))->getConstructor()): ?>
<?php $attributes = $attributes->except(collect($constructor->getParameters())->map->getName()->all()); ?>
<?php endif; ?>
<?php $component->withAttributes(['name' => 'task','height' => '20']); ?>
<?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginalce262628e3a8d44dc38fd1f3965181bc)): ?>
<?php $attributes = $__attributesOriginalce262628e3a8d44dc38fd1f3965181bc; ?>
<?php unset($__attributesOriginalce262628e3a8d44dc38fd1f3965181bc); ?>
<?php endif; ?>
<?php if (isset($__componentOriginalce262628e3a8d44dc38fd1f3965181bc)): ?>
<?php $component = $__componentOriginalce262628e3a8d44dc38fd1f3965181bc; ?>
<?php unset($__componentOriginalce262628e3a8d44dc38fd1f3965181bc); ?>
<?php endif; ?> <?php echo e(__('Task Board')); ?>                                </a>                            </td>                        </tr>                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>                    </tbody>                </table>            </div>                        <div class="mt-3 d-flex justify-content-end">                <?php echo e($orders->links()); ?>            </div>            <?php if(!$orders->count()): ?>                <h4 class="text-center text-muted"><?php echo e(__('No data found')); ?></h4>            <?php endif; ?>        </div>    </div><?php $__env->stopSection(); ?>
<?php echo $__env->make('frontend.layouts.user.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /Users/apple/Documents/gratech/resources/views/frontend/user/service/my_service.blade.php ENDPATH**/ ?>