<?php $__env->startSection('title'); ?>    <?php echo e(__('Subscriber')); ?><?php $__env->stopSection(); ?><?php $__env->startSection('content'); ?>    <div class="py-4">        <div class="d-flex justify-content-between w-100 flex-wrap">            <div class="mb-3 mb-lg-0">                <h1 class="h4"><?php echo e(__('Subscriber')); ?></h1>            </div>        </div>    </div>    <div class="card border-0 shadow mb-4">        <div class="card-body">            <div class="table-responsive">                <table class="table table-centered table-nowrap mb-0 rounded table-hover align-items-center">                    <thead class="thead-light">                    <tr>                        <th class="border-bottom"><?php echo e(__('Name')); ?></th>                        <th class="border-bottom"><?php echo e(__('Mail')); ?></th>                        <th class="border-bottom"><?php echo e(__('Join Date')); ?></th>                        <th class="border-bottom"><?php echo e(__('Action')); ?></th>                    </tr>                    </thead>                    <tbody>                    <?php $__currentLoopData = $subscribers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $subscriber): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>                        <tr>                            <td><span class="fw-bold"><?php echo e($subscriber->name); ?></span></td>                            <td><span class="fw-bold"><?php echo e($subscriber->email); ?></span></td>                            <td><span class="fw-bold"><?php echo e($subscriber->created_at->format('Y-m-d')); ?></span></td>                            <td>								<span data-id="<?php echo e($subscriber->id); ?>" title="<?php echo e(__('mail send')); ?>" class="send-mail cursor">										<?php if (isset($component)) { $__componentOriginal4bfb1fa99a7d89eae1cf7ba1287cdfc5 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal4bfb1fa99a7d89eae1cf7ba1287cdfc5 = $attributes; } ?>
<?php $component = App\View\Components\Svg::resolve(['i' => 'email'] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? (array) $attributes->getIterator() : [])); ?>
<?php $component->withName('svg'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag && $constructor = (new ReflectionClass(App\View\Components\Svg::class))->getConstructor()): ?>
<?php $attributes = $attributes->except(collect($constructor->getParameters())->map->getName()->all()); ?>
<?php endif; ?>
<?php $component->withAttributes([]); ?>
<?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal4bfb1fa99a7d89eae1cf7ba1287cdfc5)): ?>
<?php $attributes = $__attributesOriginal4bfb1fa99a7d89eae1cf7ba1287cdfc5; ?>
<?php unset($__attributesOriginal4bfb1fa99a7d89eae1cf7ba1287cdfc5); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal4bfb1fa99a7d89eae1cf7ba1287cdfc5)): ?>
<?php $component = $__componentOriginal4bfb1fa99a7d89eae1cf7ba1287cdfc5; ?>
<?php unset($__componentOriginal4bfb1fa99a7d89eae1cf7ba1287cdfc5); ?>
<?php endif; ?>								</span>                            </td>                        </tr>                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>                    </tbody>                </table>                <?php if($subscribers->count() == 0): ?>                    <h4 class="text-center text-muted py-3"><?php echo e(__('No Data Available')); ?></h4>                <?php endif; ?>            </div>        </div>    </div>        <?php echo $__env->make('backend.subscriber.partial._send_mail_modal', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php $__env->stopSection(); ?><?php $__env->startSection('script'); ?>    <script>        $(document).ready(function () {            $('.send-mail').on('click', function () {                var id = $(this).data('id');                $('#subscriber_id').val(id);                $('#send-mail-modal').modal('show');            });        });    </script><?php $__env->stopSection(); ?>
<?php echo $__env->make('backend.layouts.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /Users/apple/Documents/gratech/resources/views/backend/subscriber/index.blade.php ENDPATH**/ ?>