<?php $__env->startSection('title', __('Notifications')); ?><?php $__env->startSection('user-setting-content'); ?>    <div class="card border-0">        <div class="card-body">            <h2 class="mb-4">🔔 <?php echo e(__('All Notifications')); ?></h2>            <div class="divide-y">                <?php $__currentLoopData = $notifications; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $notification): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>                    <div>                        <div class="row">                            <div class="col-auto">                                <span class="avatar">                                     <?php if (isset($component)) { $__componentOriginalce262628e3a8d44dc38fd1f3965181bc = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginalce262628e3a8d44dc38fd1f3965181bc = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.icon','data' => ['name' => ''.e(\App\Constants\NotificationType::ICON[$notification->data['type']]).'','class' => 'text-'.e(isset($notification->data['status']) && $notification->data['status'] == 'failed' ? 'danger' : 'green').'']] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? (array) $attributes->getIterator() : [])); ?>
<?php $component->withName('icon'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag && $constructor = (new ReflectionClass(Illuminate\View\AnonymousComponent::class))->getConstructor()): ?>
<?php $attributes = $attributes->except(collect($constructor->getParameters())->map->getName()->all()); ?>
<?php endif; ?>
<?php $component->withAttributes(['name' => ''.e(\App\Constants\NotificationType::ICON[$notification->data['type']]).'','class' => 'text-'.e(isset($notification->data['status']) && $notification->data['status'] == 'failed' ? 'danger' : 'green').'']); ?>
<?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginalce262628e3a8d44dc38fd1f3965181bc)): ?>
<?php $attributes = $__attributesOriginalce262628e3a8d44dc38fd1f3965181bc; ?>
<?php unset($__attributesOriginalce262628e3a8d44dc38fd1f3965181bc); ?>
<?php endif; ?>
<?php if (isset($__componentOriginalce262628e3a8d44dc38fd1f3965181bc)): ?>
<?php $component = $__componentOriginalce262628e3a8d44dc38fd1f3965181bc; ?>
<?php unset($__componentOriginalce262628e3a8d44dc38fd1f3965181bc); ?>
<?php endif; ?>                                </span>                            </div>                            <div class="col">                                <div class="text-truncate">                                    <?php echo e($notification->data['message']); ?>                                </div>                                <div class="text-secondary"><?php echo e($notification->created_at->format('d M, Y H:i A')); ?></div>                            </div>                            <div class="col-auto align-self-center">                                <?php if($notification->read_at == null ): ?>                                    <a href="<?php echo e(route('user.notifications.markAsRead', ['id' => $notification->id])); ?>"                                       class="text-red">                                        <i class="fa-sharp fa-solid fa-bell-on"></i>                                    </a>                                <?php endif; ?>                            </div>                        </div>                    </div>                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>                <?php echo e($notifications->links()); ?>                <?php if(count($notifications) == 0): ?>                    <div class="alert alert-info">                        <?php echo e(__('No Notification found')); ?>                    </div>                <?php endif; ?>            </div>        </div>    </div><?php $__env->stopSection(); ?>
<?php echo $__env->make('frontend.user.setting.index', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /Users/apple/Documents/gratech/resources/views/frontend/user/setting/notification.blade.php ENDPATH**/ ?>