<div class="col-12 col-xxl-6">    <!-- Latest Users Card -->    <div class="card  mb-4">        <div class="card-header d-flex justify-content-between align-items-center">            <h3 class="card-title mb-0"><?php echo e(__('Latest Users')); ?></h3>        </div>        <div class="card-body p-2">            <div class="table-responsive rounded">                <table class="table table-striped mb-0">                    <thead class="table-light">                    <tr>                        <th><?php echo e(__('Name') .' | ' . __('Balance')); ?></th>                        <th><?php echo e(__('Email') .' | ' . __('Status')); ?></th>                        <th><?php echo e(__('Join Time')); ?></th>                        <th><?php echo e(__('Action')); ?></th>                    </tr>                    </thead>                    <tbody>                    <?php $__currentLoopData = $users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>                        <tr class="align-middle">                            <td>                                <div class="d-flex align-items-center">                                    <img class="rounded-circle me-2"                                         src="<?php echo e(asset($user->avatar)); ?>"                                         alt="<?php echo e($user->full_name); ?>"                                         height="40" width="40">                                    <div>                                        <div class="fw-bold"><?php echo e($user->full_name); ?></div>                                        <div class="text-muted small"><?php echo e(setting('currency_symbol').$user->getBalance()); ?></div>                                    </div>                                </div>                            </td>                            <td>                                <div class="fw-bold"><?php echo e(maskEmail($user->email)); ?></div>                                <span class="badge bg-<?php echo e($user->email_verified_at ? 'success' : 'danger'); ?>">                                        <?php echo e(strtoupper($user->email_verified_at ? __('Verified') : __('Unverified'))); ?>                                    </span>                            </td>                            <td>                                <div class="fw-bold"><?php echo e($user->created_at->format('d M, Y')); ?></div>                                <div class="text-muted small"><?php echo e($user->created_at->diffForHumans()); ?></div>                            </td>                            <td>                                <a href="<?php echo e(route('admin.users.manage', $user->id)); ?>" class="btn btn-sm btn-info">                                    <?php if (isset($component)) { $__componentOriginalce262628e3a8d44dc38fd1f3965181bc = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginalce262628e3a8d44dc38fd1f3965181bc = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.icon','data' => ['name' => 'manage','height' => '22','width' => '22']] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? (array) $attributes->getIterator() : [])); ?>
<?php $component->withName('icon'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag && $constructor = (new ReflectionClass(Illuminate\View\AnonymousComponent::class))->getConstructor()): ?>
<?php $attributes = $attributes->except(collect($constructor->getParameters())->map->getName()->all()); ?>
<?php endif; ?>
<?php $component->withAttributes(['name' => 'manage','height' => '22','width' => '22']); ?>
<?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginalce262628e3a8d44dc38fd1f3965181bc)): ?>
<?php $attributes = $__attributesOriginalce262628e3a8d44dc38fd1f3965181bc; ?>
<?php unset($__attributesOriginalce262628e3a8d44dc38fd1f3965181bc); ?>
<?php endif; ?>
<?php if (isset($__componentOriginalce262628e3a8d44dc38fd1f3965181bc)): ?>
<?php $component = $__componentOriginalce262628e3a8d44dc38fd1f3965181bc; ?>
<?php unset($__componentOriginalce262628e3a8d44dc38fd1f3965181bc); ?>
<?php endif; ?>                                </a>                            </td>                        </tr>                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>                    </tbody>                </table>            </div>        </div>    </div></div><?php /**PATH /Users/apple/Documents/gratechcms/resources/views/backend/dashboard/partial/_latest_user.blade.php ENDPATH**/ ?>