<a class="nav-link text-dark notification-bell <?php echo e($notifications->count() > 0 ? 'unread' : ''); ?> dropdown-toggle"   data-unread-notifications="true" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">    <?php if (isset($component)) { $__componentOriginalce262628e3a8d44dc38fd1f3965181bc = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginalce262628e3a8d44dc38fd1f3965181bc = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.icon','data' => ['name' => 'bell-1']] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? (array) $attributes->getIterator() : [])); ?>
<?php $component->withName('icon'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag && $constructor = (new ReflectionClass(Illuminate\View\AnonymousComponent::class))->getConstructor()): ?>
<?php $attributes = $attributes->except(collect($constructor->getParameters())->map->getName()->all()); ?>
<?php endif; ?>
<?php $component->withAttributes(['name' => 'bell-1']); ?>
<?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginalce262628e3a8d44dc38fd1f3965181bc)): ?>
<?php $attributes = $__attributesOriginalce262628e3a8d44dc38fd1f3965181bc; ?>
<?php unset($__attributesOriginalce262628e3a8d44dc38fd1f3965181bc); ?>
<?php endif; ?>
<?php if (isset($__componentOriginalce262628e3a8d44dc38fd1f3965181bc)): ?>
<?php $component = $__componentOriginalce262628e3a8d44dc38fd1f3965181bc; ?>
<?php unset($__componentOriginalce262628e3a8d44dc38fd1f3965181bc); ?>
<?php endif; ?></a><div class="dropdown-menu dropdown-menu-lg dropdown-menu-center mt-3 py-0 ms-4">    <div class="list-group list-group-flush">        <a href="javascript:void(0)" class="text-center text-primary fw-bold border-bottom border-light py-3"><?php echo e(__('Notifications')); ?></a>        <div id="notificationList">            <?php $__currentLoopData = $notifications; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $notification): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>                <a href="<?php echo e($notification->data['action_link']); ?>" data-id="<?php echo e($notification->id); ?>"                   class="list-group-item list-group-item-action border-bottom read-notification">                    <div class="row align-items-center">                        <div class="col-auto">                            <img src="<?php echo e(asset($notification->data['user_avatar'])); ?>" class="avatar-md rounded" alt="">                        </div>                        <div class="col ps-0 ms-2">                            <div class="d-flex justify-content-between align-items-center">                                <h4 class="h6 mb-0 text-small"><?php echo e($notification->data['user_name']); ?></h4>                                <small class="text-success"><?php echo e($notification->created_at->diffForHumans()); ?></small>                            </div>                            <p class="font-small mt-1 mb-0"><?php echo e($notification->data['message']); ?></p>                        </div>                    </div>                </a>            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>        </div>        <?php if($notifications->isEmpty()): ?>            <h5 class="text-center text-muted py-3"><?php echo e(__('No new notifications')); ?></h5>        <?php endif; ?>        <div class="d-flex justify-content-between p-2">            <?php if(!$notifications->isEmpty()): ?>                <a href="<?php echo e(route('admin.notifications.read-all')); ?>" class="btn btn-sm btn-info">                    <i class="fa-sharp fa-solid fa-bell me-1"></i> <?php echo e(__('Mark all as read')); ?>                </a>            <?php endif; ?>            <a href="<?php echo e(route('admin.notifications.index')); ?>" class="btn btn-sm btn-tertiary <?php echo e($notifications->count() == 0 ? 'w-100' : ''); ?>">                <i class="fa-sharp fa-solid fa-eye me-1"></i> <?php echo e(__('View all')); ?>            </a>        </div>    </div></div><?php /**PATH /Users/apple/Documents/gratech/resources/views/backend/layouts/partials/_notification_dropdown.blade.php ENDPATH**/ ?>