<?php $__env->startSection('title', __('User Statistics')); ?><?php $__env->startSection('user_sub_content'); ?>    <div class="row mt-3">        <?php $__currentLoopData = $cardStatistics; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $statistic): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>            <div class="col-sm-6 col-lg-4 p-2">                <div class="card card-sm">                    <div class="card-body p-2">                        <div class="row align-items-center">                            <div class="col-auto">                                <div class="icon-shape icon-shape-<?php echo e($statistic['color']); ?> rounded me-2 me-sm-0">                                    <?php if (isset($component)) { $__componentOriginalce262628e3a8d44dc38fd1f3965181bc = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginalce262628e3a8d44dc38fd1f3965181bc = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.icon','data' => ['name' => $statistic['icon'],'class' => 'icon']] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? (array) $attributes->getIterator() : [])); ?>
<?php $component->withName('icon'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag && $constructor = (new ReflectionClass(Illuminate\View\AnonymousComponent::class))->getConstructor()): ?>
<?php $attributes = $attributes->except(collect($constructor->getParameters())->map->getName()->all()); ?>
<?php endif; ?>
<?php $component->withAttributes(['name' => \Illuminate\View\Compilers\BladeCompiler::sanitizeComponentAttribute($statistic['icon']),'class' => 'icon']); ?>
<?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginalce262628e3a8d44dc38fd1f3965181bc)): ?>
<?php $attributes = $__attributesOriginalce262628e3a8d44dc38fd1f3965181bc; ?>
<?php unset($__attributesOriginalce262628e3a8d44dc38fd1f3965181bc); ?>
<?php endif; ?>
<?php if (isset($__componentOriginalce262628e3a8d44dc38fd1f3965181bc)): ?>
<?php $component = $__componentOriginalce262628e3a8d44dc38fd1f3965181bc; ?>
<?php unset($__componentOriginalce262628e3a8d44dc38fd1f3965181bc); ?>
<?php endif; ?>                                </div>                            </div>                            <div class="col">                                <div class="font-weight-medium">                                    <?php echo e($statistic['title']); ?>                                </div>                                <div class="text-muted text-nowrap">                                    <?php echo e($statistic['value']); ?>                                </div>                            </div>                        </div>                    </div>                </div>            </div>        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>    </div>    <div class="row mt-3">        <div class="col-md-12">            <div class="card">                <div class="card-header d-flex justify-content-between align-items-center">                    <h3 class="card-title mb-0"><?php echo e(__('Transactions Statistics')); ?></h3>                    <div class="col-3">                        <input type="text" name="daterange" id="user-daterange-transactions" class="form-control pt-0 pb-0" value="<?php echo e($dateRange); ?>" placeholder="<?php echo e(__('Select a date range')); ?>" />                    </div>                </div>                <div class="card-body">                    <div id="user-transactions-chart" class="chart-lg"></div>                </div>            </div>        </div>    </div><?php $__env->stopSection(); ?><?php $__env->startPush('script'); ?>    <?php echo $__env->make('backend.user.partial._script', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php $__env->stopPush(); ?>
<?php echo $__env->make('backend.user.manage', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /Users/apple/Documents/gratech/resources/views/backend/user/info.blade.php ENDPATH**/ ?>